//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.16 at 07:03:41 AM EET 
//


package ua.epam.sergiishapoval.projects.xmlxsd.voucher;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for hotelProps complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="hotelProps">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="stars" type="{}first5Positive"/>
 *         &lt;element name="meals" type="{}meals"/>
 *         &lt;element name="roomPlaces" type="{}first5Positive"/>
 *         &lt;element name="condition" type="{}presenceSign"/>
 *         &lt;element name="TV" type="{}presenceSign"/>
 *         &lt;element name="WIFI" type="{}presenceSign"/>
 *         &lt;element name="freeParking" type="{}presenceSign"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "hotelProps", propOrder = {
    "stars",
    "meals",
    "roomPlaces",
    "condition",
    "tv",
    "wifi",
    "freeParking"
})
public class HotelProps {

    @XmlSchemaType(name = "positiveInteger")
    protected int stars;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected Meals meals;
    @XmlSchemaType(name = "positiveInteger")
    protected int roomPlaces;
    @XmlElement(required = true)
    protected String condition;
    @XmlElement(name = "TV", required = true)
    protected String tv;
    @XmlElement(name = "WIFI", required = true)
    protected String wifi;
    @XmlElement(required = true)
    protected String freeParking;

    /**
     * Gets the value of the stars property.
     * 
     */
    public int getStars() {
        return stars;
    }

    /**
     * Sets the value of the stars property.
     * 
     */
    public void setStars(int value) {
        this.stars = value;
    }

    /**
     * Gets the value of the meals property.
     * 
     * @return
     *     possible object is
     *     {@link Meals }
     *     
     */
    public Meals getMeals() {
        return meals;
    }

    /**
     * Sets the value of the meals property.
     * 
     * @param value
     *     allowed object is
     *     {@link Meals }
     *     
     */
    public void setMeals(Meals value) {
        this.meals = value;
    }

    /**
     * Gets the value of the roomPlaces property.
     * 
     */
    public int getRoomPlaces() {
        return roomPlaces;
    }

    /**
     * Sets the value of the roomPlaces property.
     * 
     */
    public void setRoomPlaces(int value) {
        this.roomPlaces = value;
    }

    /**
     * Gets the value of the condition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCondition() {
        return condition;
    }

    /**
     * Sets the value of the condition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCondition(String value) {
        this.condition = value;
    }

    /**
     * Gets the value of the tv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTV() {
        return tv;
    }

    /**
     * Sets the value of the tv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTV(String value) {
        this.tv = value;
    }

    /**
     * Gets the value of the wifi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWIFI() {
        return wifi;
    }

    /**
     * Sets the value of the wifi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWIFI(String value) {
        this.wifi = value;
    }

    /**
     * Gets the value of the freeParking property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeParking() {
        return freeParking;
    }

    /**
     * Sets the value of the freeParking property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeParking(String value) {
        this.freeParking = value;
    }

    @Override
    public String toString() {
        return "HotelProps{" +
                "stars=" + stars +
                ", meals=" + meals +
                ", roomPlaces=" + roomPlaces +
                ", condition='" + condition + '\'' +
                ", tv='" + tv + '\'' +
                ", wifi='" + wifi + '\'' +
                ", freeParking='" + freeParking + '\'' +
                '}';
    }
}
