//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.16 at 07:03:41 AM EET 
//


package ua.epam.sergiishapoval.projects.xmlxsd.voucher;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for meals.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="meals">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="HB"/>
 *     &lt;enumeration value="BB"/>
 *     &lt;enumeration value="Al"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "meals")
@XmlEnum
public enum Meals {

    HB("HB"),
    BB("BB"),
    @XmlEnumValue("Al")
    AL("Al");
    private final String value;

    Meals(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Meals fromValue(String v) {
        for (Meals c: Meals.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
